// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCa1OIwJ46gEANIJSJ-N6ZkI2dthvDrugs',
    appId: '1:1082852302068:web:4cc48fed29ae11db2fd2a1',
    messagingSenderId: '1082852302068',
    projectId: 'project-ewise',
    authDomain: 'project-ewise.firebaseapp.com',
    storageBucket: 'project-ewise.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDw-BOaNbOEoq2kaclVhSQGLNXCkJWy2SY',
    appId: '1:1082852302068:android:8f74b3dcfae9d6b52fd2a1',
    messagingSenderId: '1082852302068',
    projectId: 'project-ewise',
    storageBucket: 'project-ewise.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvN7kmP0alQnp8mB2HpnzfhoE_8Su5viI',
    appId: '1:1082852302068:ios:83660521d97c1e5e2fd2a1',
    messagingSenderId: '1082852302068',
    projectId: 'project-ewise',
    storageBucket: 'project-ewise.appspot.com',
    androidClientId: '1082852302068-f0s5kh5o775ipmij4m2pjnelq6jtguu5.apps.googleusercontent.com',
    iosClientId: '1082852302068-21iq7coragbjac84ohsdmpuf90d9d0ei.apps.googleusercontent.com',
    iosBundleId: 'com.example.ewise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvN7kmP0alQnp8mB2HpnzfhoE_8Su5viI',
    appId: '1:1082852302068:ios:f7508a6290ebfa732fd2a1',
    messagingSenderId: '1082852302068',
    projectId: 'project-ewise',
    storageBucket: 'project-ewise.appspot.com',
    androidClientId: '1082852302068-f0s5kh5o775ipmij4m2pjnelq6jtguu5.apps.googleusercontent.com',
    iosClientId: '1082852302068-l15l80mset9i6p62bbtc0r91ntmckq75.apps.googleusercontent.com',
    iosBundleId: 'com.example.ewise.RunnerTests',
  );
}
